<section class="basic-info">
    <h2>Itálie</h2>
    <div class="cast">
    <div class="rozdeleni"></div>
    <p>Itálie (italsky Italia), plným názvem Italská republika (italsky Repubblica Italiana), je stát ležící v jižní a západní Evropě. Skládá se z Apeninského poloostrova zasahujícího do Středozemního moře, na jehož severní hranici se nachází Alpy, a dále z téměř 800 ostrovů. K největším a nejvýznamnějším patří Sicílie a Sardinie. Itálie sousedí na západě s Francií, na severu se Švýcarskem a Rakouskem, na východě se Slovinskem, a také se dvěma enklávami – Vatikánem a San Marinem. Povrch země je převážně hornatý a středomořské podnebí je výrazně ovlivněno mořem. Itálie se dělí na 20 regionů, na ploše přibližně 301 000 km² zde žije asi 59 milionů obyvatel. Je desátou největší zemí evropského kontinentu podle rozlohy a třetím nejlidnatějším členským státem Evropské unie. Hlavním a největším městem je Řím, mezi další významná města patří Milán, Neapol, Turín a Palermo. Drtivou většinu obyvatel tvoří Italové, úředním jazykem je italština a přibližně 84 % obyvatel se hlásí ke katolické církvi.
    Apeninský poloostrov byl historicky domovem mnoha starověkých národů. Latinské město Řím ve střední Itálii, původně založené jako království, se stalo republikou, která si podmanila Středomoří a po staletí mu vládla jako říše. S rozšířením křesťanství se Řím stal sídlem katolické církve a papežství. Během raného středověku zažila Itálie pád Západořímské říše a období stěhování germánských kmenů. Do 11. století se italské městské státy a námořní republiky rozvinuly a díky obchodu dosáhly značné prosperity, čímž položily základy moderního kapitalismu. Italská renesance vzkvétala v 15. a 16. století zejména ve Florencii a postupně se rozšířila do celé Evropy. Italští objevitelé objevili nové cesty na Dálný východ i do Nového světa a přispěli tak k evropskému věku zámořských objevů. Dlouhotrvající rivalita mezi městskými státy však vedla k tomu, že Apeninský poloostrov zůstal až do novověku politicky roztříštěný. V průběhu 17. a 18. století hospodářský a obchodní význam Itálie výrazně poklesl.
    Po staletích politického a územního rozdělení byla Itálie v roce 1861 po válkách za nezávislost téměř úplně sjednocena a vzniklo Italské království. Od konce 19. století do začátku 20. století se země rychle industrializovala, především na severu, a vytvořila koloniální říši, zatímco jih zůstal převážně chudý, což vedlo k rozsáhlé emigraci obyvatel do Ameriky. V letech 1915–1918 se Itálie účastnila první světové války na straně Dohody. V roce 1922 byla po období politické nestability nastolena fašistická diktatura. Během druhé světové války byla Itálie nejprve součástí Osy, později se vzdala spojencům a následně se podílela na odporu proti nacistické okupaci. Po skončení války byla monarchie nahrazena republikou a země zažila dlouhé období hospodářského růstu, díky němuž se stala vyspělou ekonomikou.
    Itálie je unitární parlamentní republikou, v níž je prezident ceremoniální hlavou státu a zákonodárnou moc vykonává dvoukomorový parlament. Patří mezi největší ekonomiky světa, má vyspělý průmysl a hraje významnou roli v regionálních i globálních hospodářských, kulturních a diplomatických záležitostech. Je považována za kulturní velmoc a dlouhodobě patří mezi světová centra umění, hudby, literatury, kuchyně, vědy, techniky a módy. Itálie má největší počet památek světového dědictví na světě a je jednou z nejnavštěvovanějších zemí. Je zakládajícím členem Evropské unie a členem řady mezinárodních organizací, včetně NATO a skupiny G7</p>
    <div class="foto"><img src="vlajka.svg" alt="Vlajka"></div></div>
</section>