<section>
    <h2>Známé Osobnosti</h2>
    <h3>Enzo Ferrari</h3>
    <div class="cast">
    <div class="rozdeleni"></div>
    <p>Enzo Anselmo „Commendatore“ Ferrari (18. února 1898 Modena - 14. srpna 1988 Modena) byl italský automobilový závodník, zakladatel a manažer závodního týmu Scuderia Ferrari a zakladatel automobilky Ferrari.
    Narodil se 18. února 1898 v Modeně Alfredovi a Adalgise Ferrariovým (rozená Bisbiniová). Oficiálním datem jeho narození je až 20. únor, údajně kvůli sněhové kalamitě otec nemohl vyjít z domu a do matriky ho nechal zapsat až o tři dny po narození.
    Enzo Ferrari získal jen základní vzdělání. Jeho starší bratr Alfred, přezdívaný Dino, si v rodinném sídle zařídil dílnu, kde pak pracoval i Enzo a jejich otec. V roce 1915 zemřel jeho otec na zápal plic a v následujícím roce i bratr Alfred, který odešel jako dobrovolník do války. Enzo narukoval v roce 1917 a sloužil u 3. horského dělostřeleckého pluku italské armády. V roce 1918 onemocněl španělskou chřipkou, ale přežil a byl propuštěn do civilu.
    Netroufl si však udržet dílnu bez otce a bratra. Hledal práci v automobilce FIAT v Turíně, ale byl odmítnut, našel si tedy nové zaměstnání. Stal se testovacím řidičem společnosti C.M.N. (Costruzioni Meccaniche Nazionali) v Miláně. Roku 1919 absolvoval svůj první závod na trati Parma - Poggio di Berceto. V listopadu téhož roku se zúčastnil závodu Targa Florio na Sicílii. O rok později již byl závodním jezdcem továrního týmu Alfa Romeo. Jeho ekonomická situace se zlepšila a v roce 1923 se oženil se švadlenou Laurou Garellovou. V roce 1929 založil vlastní závodní tým, který nazval Scuderia Ferrari. Roku 1932 závodní kariéru ukončil, nechtěl již dále riskovat život po narození prvního syna Alfreda.</p>
    <div class="foto"><img src="enzo.jpg" alt="Enzo Ferrari"></div></div>

    <h3>Leonardo Da Vinci</h3>
    <div class="cast">
    <div class="foto"><img src="davinci.jpg" alt="Leonardo Da Vinci"></div>
    <div class="rozdeleni"></div>
    <p>Leonardo da Vinci, rodným jménem Leonardo di ser Piero (15. dubna 1452 Anchiano u Vinci, Itálie - 2. května 1519 Le Clos Lucé u Amboise, Francie) byl italský malíř, čelný představitel renesanční malby, mimo jiné autor nejslavnějšího obrazu všech dob, portrétu zvaného Mona Lisa (kolem 1503-1507, Louvre, Paříž). Proslul také jako všestranná renesanční osobnost: vedle malířství byl i sochař, architekt, přírodovědec, hudebník, spisovatel, vynálezce a konstruktér. Nemalou měrou se podílel také na zdůrazňování práv zvířat, s čímž pravděpodobně souvisel i jeho možný vegetariánský jídelníček.</p></div>

    <h3>Valentino Rossi</h3>
    <div class="cast">
    <div class="rozdeleni"></div>
    <p>Valentino Rossi (* 16. února 1979 Urbino) je bývalý italský profesionální motocyklový závodník a devítinásobný mistr světa, z toho 7x zvítězil v tzv. královské kubatuře třídy MotoGP, 1x v kubatuře 125 cm³ a 1x v kubatuře 250 cm³ v Mistrovství světa silničních motocyklů. Obecně je považován za jednoho z nejlepších motocyklových jezdců všech dob.
    V roce 2006 mu jen těsně unikl osmý titul mistra světa a v sezóně 2007 se před něj dostal Casey Stoner až v roce 2008 opět titul získal. Podle amerického sportovního týdeníku Sports Illustrated je sedmým nejvýdělečnějším sportovcem světa a druhým, který žije mimo Spojené státy americké. Odhaduje se, že jeho roční příjmy dosahují 30 milionů dolarů.
    V mládí šel ve stopách svého otce, Graziana Rossiho. V mistrovství světa začal za tým Aprilia závodit v roce 1996 ve třídě do 125 cm³ a hned následující rok zvítězil a stal se mistrem světa. V následujícím roce už za Aprilii startoval ve třídě do 250 cm³ a v roce 1999 zvítězil i v této třídě. V roce 2001 vyhrál třídu do 500 cm³, v té době za tým Honda. V sérii úspěchů pokračoval i v královské třídě MotoGP (bývalá třída do 500 cm³) i v letech 2002 a 2003. V týmu Yamaha získal titul mistra světa i v letech 2004 a 2005. Šestý titul v řadě mu v roce 2006 těsně unikl a musel se spokojit s celkovým druhým místem za Nicky Haydenem. V sezóně 2007 obsadil třetí místo, poslední závod této sezóny kvůli zlomenině ruky nedokončil. Druhé místo obsadil Dani Pedrosa a mistrem světa se stal Casey Stoner. Sezónu 2008 odstartoval vítězstvím v GP Číny svou úspěšnou sezonu s jeho rivalem Casey Stonerem. Rossi v této sezoně překonal hranici 90 vítězství čímž překonal Angela Nieta. V závodě v japonském Motegi si zajistil titul mistra světa pro rok 2008. V následující sezoně vyhrál 6 závodů a v Sepangu si zajistil svůj devátý titul mistra světa. V tomto roce také získal v nizozemském Assenu své sté vítězství a stal se tak druhým jezdcem v historii, který překonal hranici sta vítězství. Sezóna 2010 pro něho nebyla úspěšná, protože si poranil šlachy v rameni během tréninku na motocrossové motorce. Sice vyhrál úvodní závod v Kataru, ale již při tréninku ve čtvrté GP Itálie v Mugellu si po pádu přivodil otevřenou zlomeninu holenní kosti na pravé noze. Kvůli tomuto zranění poprvé vynechal závod v Grand Prix. Vrátil se až po čtyřech závodech a to na GP Německa. Zranění ramene a nepříliš dobré výsledky znamenaly vzestup jeho týmového kolegy Jorge Lorenza. Ten se také měl stát týmovou jedničkou a odsunul Valentina Rossiho na druhou pozici. Proto se Rossi rozhodl o ukončení spolupráce s Yamahou a podepsal kontrakt na dva roky s továrnou Ducati. Již při testu ve Valencii nebyl však s motorkou spokojený, čímž začaly technické problémy s motocyklem Ducati.</p>
    <div class="foto"><img src="rossi.jpg" alt="Valentino Rossi"></div></div>

    <h3>Paolo Maldini</h3>
    <div class="cast">
    <div class="foto"><img src="maldini.jpg" alt="Maldini"></div>
    <div class="rozdeleni"></div>
    <p>Paolo Cesare Maldini (26. června 1968, Milán, Itálie) je sportovní manažer a bývalý italský fotbalový obránce. S reprezentací se stal vicemistrem světa v roce 1994 a vicemistrem Evropy v roce 2000.
    Byl to jeden z nejlepších fotbalových obránců v historii. Během své kariéry, která trvala 25 let, hrál jen za jediný klub: AC Milán. Vyhrál celkem 26 trofejí: 7 titulů, 1 domácí pohár, 5 domácích superpohárů, 5 Lig mistrů + PMEZ (8 odehraných finále), 5 evropských superpohárů, 2 interkontinentální poháry a 1 Mistrovství světa klubů. Se spoluhráči Tassottim, Baresim a Costacurtou tvořili jednu z nejlepších obranných linií v historii fotbalu, což umožnilo AC Milán vytvořit rekord v po sobě jdoucích zápasech bez porážky - 58 zápasů od 26. května 1991 do 14. března 1993.
    Od roku 1988 do roku 2002 hrál za národní tým Itálie, jehož byl osm let kapitánem. Zúčastnil se čtyř turnajů mistrovství světa (1990, 1994, 1998 a 2002) a tří turnajů mistrovství Evropy (1988, 1996 a 2000). V reprezentaci vytvořil rekord v počtu odehraných utkání i v počtu utkání jako kapitán. Oba rekordy byly později překonány.
    Od roku 2005 až do roku 2020 držel rekord s největším počtem utkání v italské lize. V soutěžích UEFA je se 174 utkáními čtvrtý, přičemž mezi Italy první. Je také hráčem, který má nejvíce utkání v dresu Rossoneri - celkem 902. V individuálních anketách byl nejlépe na 3. místě v Zlatém míči v letech 1994 a 2003. V roce 2002 byl zařazen do FIFA World Cup Dream Team (výběr nejlepších jedenácti hráčů v historii MS) a v roce 2004 byl zařazen do FIFA 100 (seznam 125 nejlepších hráčů u příležitosti stého výročí FIFA). V roce 2020 byl zařazen do týmu Zlatý míč - nejlepší tým.
    Jeho otec, Cesare Maldini, patří také k nejznámějším italským fotbalovým reprezentantům všech dob.</p></div>
</section>